project:
  type: website
  output-dir: docs
  post-render: "scripts/decktape.sh"   
  render:
    - "*.qmd"
    - "!assignments/files/"
    - "!files/tutorials/"  
 

website:
  title: "EC306 - Wages and Employment"
  navbar:
    pinned: true
    background: "#9e32a8"
    left:
      - href: index.qmd
        text: Home
      - syllabus.qmd
      - text: "Content"
        file: content/index.qmd
      - text: "Assignments"
        file: assignments/index.qmd

  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      background: dark
      contents:
      
        - section: "Overview"
          contents:
            - content/index.qmd
        - section: "Course content"
          contents:
            - text: "Intro to Labour Economics"
              file: content/introtolme.qmd
            - text: "Labour Supply 1: Individual Attachment to the Labour Market" 
              file: content/lsupply1.qmd  
#            - text: "Labour Supply 2: Labour Supply and Public Policy"
#              file: content/lsupply2.qmd   
#            - text: "Introduction to Stata"
#              file: content/introtostata.qmd
#            - text: "Labour Supply 3: Labour Supply Over the Life Cycle"
#              file: content/lsupply3.qmd   
#            - text: "Labour Demand 1: Competitive Labour Markets"
#              file: content/ldemand1.qmd
#            - text: "Labour Demand 2: Non-wage Benefits and Quasi-fixed Costs"
#              file: content/ldemand2.qmd                
#            - text: "Wages and Employment in a Single Labour Market"
#              file: content/lmarket.qmd  
#            - text: "Human Capital Theory"
#              file: content/hcapital.qmd 
#            - text: "Discrimination and Male-Female Earnings Differentials"
#              file: content/discrim.qmd 
              
    - title: "Assignments"
      style: "docked"
      search: false
      background: dark
      contents:
      
        - section: "Overview"
          contents:
            - assignments/index.qmd
           
              
format:
  html:
    code-overflow: wrap
    theme: 
      - litera
      - html/custom.scss
    toc: true


