---
title: "Assignment 1"
---


## Description

In this assignment you are asked to manipulate data, estimate statistical relationships, and interpret the findings. The questions are based the labour supply responses of women to the reduction in child care availability that accompanied the COVID-19 pandemic in the United States.  The assignment is designed to give you practice with data analysis in Stata, and to help you understand how economists use data to answer questions about economic behavior.

## Instructions

### Questions

The document below contains the assignment questions. Please provide all answers in the space below each question.  If the question requires any Stata code, please include the code relevant to that question in the space provided.  Also include the relevant output.  Note: output must be reformatted into a professional-looking table or figure.  Do not simply copy and paste (or screenshot) the Stata output. 

[{{< fa solid file-export >}} `ec306assign1.docx`](/assignments/files/ec306assign1.docx)

When you save the file to your computer, please rename it with your family name and student number, with no spaces.

### Data analysis

The data come from the US Current Population Survey (CPS).  It contains a host of information, but for this assignment the important variables are labour force participation, unemployment, the number of children in the household, and a set of demographics.  The sample for this assignment contains **women aged 25–54** and spans the **9 months before and after March 2020**.


The data file is linked below. 

[{{< fa solid file-export >}} `ec306assign1.dta`](/assignments/files/ec306assign1.dta)

### Submission

When you are finished, you are required to submit three documents according to the following instructions:

-   Your .do and .log file. **Submit this in MyLearningSpace only.**
-   A rendered PDF of your answers to the questions. **Submit this in both MyLearningSpace and Gradescope.**

### Plagiarism

This is an independent assignment, which I expect you to complete on your own. It is plagiarism to copy someone else's work verbatim, which includes Stata code. Any work you submit should be yours only. However, you are encouraged to talk to each other to try to figure out how to do the assignment.
